version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.22
      nodejs: 18
    commands:
      - echo "Installing CDK CLI..."
      - npm install -g aws-cdk

  build:
    commands:
      - echo "📂 Changing to CDK app directory"
      - cd cdk-app
      - echo "🕵️ Current directory: $(pwd)"
      - echo "📁 Contents of ../services:"
      - ls -la ../services
      - echo "📦 Tidying Go modules"
      - go mod tidy
      - echo "🧪 Synthesizing CDK app"
      - go run . synth
      - echo "🚀 Deploying CDK stack"
      - cdk deploy --require-approval never --app "go run main.go"
